/* 
 * Copyright (C) 2018 csp98
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package InterfazGrafica;

import Ahorcado.Palabra;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

public class AhorcadoGUI extends javax.swing.JFrame {

    private Palabra p;
    private String solucion;
    private int errores = 0;
    private final int MAX_ERRORES = 7;

    public AhorcadoGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jugarButton = new javax.swing.JButton();
        rendirseButton = new javax.swing.JButton();
        QButton = new javax.swing.JButton();
        RButton = new javax.swing.JButton();
        SButton = new javax.swing.JButton();
        TButton = new javax.swing.JButton();
        UButton = new javax.swing.JButton();
        VButton = new javax.swing.JButton();
        WButton = new javax.swing.JButton();
        XButton = new javax.swing.JButton();
        YButton = new javax.swing.JButton();
        ZButton = new javax.swing.JButton();
        HButton = new javax.swing.JButton();
        FButton = new javax.swing.JButton();
        EButton = new javax.swing.JButton();
        JButton = new javax.swing.JButton();
        KButton = new javax.swing.JButton();
        PButton = new javax.swing.JButton();
        LButton = new javax.swing.JButton();
        MButton = new javax.swing.JButton();
        NButton = new javax.swing.JButton();
        EnieButton = new javax.swing.JButton();
        OButton = new javax.swing.JButton();
        BButton = new javax.swing.JButton();
        AButton = new javax.swing.JButton();
        DButton = new javax.swing.JButton();
        CButton = new javax.swing.JButton();
        GButton = new javax.swing.JButton();
        IButton = new javax.swing.JButton();
        vistaPalabra1 = new InterfazGrafica.VistaPalabra();
        vistaVidas1 = new InterfazGrafica.VistaVidas();
        vistaDibujo1 = new InterfazGrafica.VistaDibujo();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(28, 28));

        jugarButton.setText("Jugar otra vez");
        jugarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugarButtonActionPerformed(evt);
            }
        });

        rendirseButton.setText("¡Me rindo!");
        rendirseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rendirseButtonActionPerformed(evt);
            }
        });

        QButton.setText("Q");
        QButton.setMaximumSize(new java.awt.Dimension(40, 40));
        QButton.setMinimumSize(new java.awt.Dimension(23, 31));
        QButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QButtonActionPerformed(evt);
            }
        });

        RButton.setText("R");
        RButton.setMaximumSize(new java.awt.Dimension(40, 40));
        RButton.setMinimumSize(new java.awt.Dimension(23, 31));
        RButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RButtonActionPerformed(evt);
            }
        });

        SButton.setText("S");
        SButton.setMaximumSize(new java.awt.Dimension(40, 40));
        SButton.setMinimumSize(new java.awt.Dimension(23, 31));
        SButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SButtonActionPerformed(evt);
            }
        });

        TButton.setText("T");
        TButton.setMaximumSize(new java.awt.Dimension(40, 40));
        TButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TButtonActionPerformed(evt);
            }
        });

        UButton.setText("U");
        UButton.setMaximumSize(new java.awt.Dimension(40, 40));
        UButton.setMinimumSize(new java.awt.Dimension(23, 31));
        UButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UButtonActionPerformed(evt);
            }
        });

        VButton.setText("V");
        VButton.setMaximumSize(new java.awt.Dimension(40, 40));
        VButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VButtonActionPerformed(evt);
            }
        });

        WButton.setText("W");
        WButton.setMaximumSize(new java.awt.Dimension(40, 40));
        WButton.setMinimumSize(new java.awt.Dimension(23, 31));
        WButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WButtonActionPerformed(evt);
            }
        });

        XButton.setText("X");
        XButton.setMaximumSize(new java.awt.Dimension(40, 40));
        XButton.setMinimumSize(new java.awt.Dimension(23, 31));
        XButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XButtonActionPerformed(evt);
            }
        });

        YButton.setText("Y");
        YButton.setMaximumSize(new java.awt.Dimension(40, 40));
        YButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YButtonActionPerformed(evt);
            }
        });

        ZButton.setText("Z");
        ZButton.setMaximumSize(new java.awt.Dimension(40, 40));
        ZButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZButtonActionPerformed(evt);
            }
        });

        HButton.setText("H");
        HButton.setMaximumSize(new java.awt.Dimension(40, 40));
        HButton.setMinimumSize(new java.awt.Dimension(23, 31));
        HButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HButtonActionPerformed(evt);
            }
        });

        FButton.setText("F");
        FButton.setMaximumSize(new java.awt.Dimension(40, 40));
        FButton.setMinimumSize(new java.awt.Dimension(23, 31));
        FButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FButtonActionPerformed(evt);
            }
        });

        EButton.setText("E");
        EButton.setMaximumSize(new java.awt.Dimension(40, 40));
        EButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EButtonActionPerformed(evt);
            }
        });

        JButton.setText("J");
        JButton.setMaximumSize(new java.awt.Dimension(40, 40));
        JButton.setMinimumSize(new java.awt.Dimension(23, 31));
        JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonActionPerformed(evt);
            }
        });

        KButton.setText("K");
        KButton.setMaximumSize(new java.awt.Dimension(40, 40));
        KButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KButtonActionPerformed(evt);
            }
        });

        PButton.setText("P");
        PButton.setMaximumSize(new java.awt.Dimension(40, 40));
        PButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PButtonActionPerformed(evt);
            }
        });

        LButton.setText("L");
        LButton.setMaximumSize(new java.awt.Dimension(40, 40));
        LButton.setMinimumSize(new java.awt.Dimension(23, 31));
        LButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LButtonActionPerformed(evt);
            }
        });

        MButton.setText("M");
        MButton.setMaximumSize(new java.awt.Dimension(40, 40));
        MButton.setMinimumSize(new java.awt.Dimension(23, 31));
        MButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MButtonActionPerformed(evt);
            }
        });

        NButton.setText("N");
        NButton.setMaximumSize(new java.awt.Dimension(40, 40));
        NButton.setMinimumSize(new java.awt.Dimension(23, 31));
        NButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NButtonActionPerformed(evt);
            }
        });

        EnieButton.setText("Ñ");
        EnieButton.setMaximumSize(new java.awt.Dimension(40, 40));
        EnieButton.setMinimumSize(new java.awt.Dimension(23, 31));
        EnieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnieButtonActionPerformed(evt);
            }
        });

        OButton.setText("O");
        OButton.setMaximumSize(new java.awt.Dimension(40, 40));
        OButton.setMinimumSize(new java.awt.Dimension(23, 31));
        OButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OButtonActionPerformed(evt);
            }
        });

        BButton.setText("B");
        BButton.setMaximumSize(new java.awt.Dimension(40, 40));
        BButton.setMinimumSize(new java.awt.Dimension(23, 31));
        BButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BButtonActionPerformed(evt);
            }
        });

        AButton.setText("A");
        AButton.setMaximumSize(new java.awt.Dimension(40, 40));
        AButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AButtonActionPerformed(evt);
            }
        });

        DButton.setText("D");
        DButton.setMaximumSize(new java.awt.Dimension(40, 40));
        DButton.setMinimumSize(new java.awt.Dimension(23, 31));
        DButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DButtonActionPerformed(evt);
            }
        });

        CButton.setText("C");
        CButton.setMaximumSize(new java.awt.Dimension(40, 40));
        CButton.setMinimumSize(new java.awt.Dimension(23, 31));
        CButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CButtonActionPerformed(evt);
            }
        });

        GButton.setText("G");
        GButton.setMaximumSize(new java.awt.Dimension(40, 40));
        GButton.setMinimumSize(new java.awt.Dimension(23, 31));
        GButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GButtonActionPerformed(evt);
            }
        });

        IButton.setText("I");
        IButton.setMaximumSize(new java.awt.Dimension(40, 40));
        IButton.setMinimumSize(new java.awt.Dimension(23, 31));
        IButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(AButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(UButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(VButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(WButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(XButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(YButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ZButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(KButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(MButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(NButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(EnieButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16)
                                        .addComponent(OButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(PButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(vistaDibujo1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(CButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(DButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(EButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(FButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(GButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(HButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(QButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(IButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(vistaPalabra1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jugarButton)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(388, 388, 388)
                                    .addComponent(rendirseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(364, 364, 364)
                                    .addComponent(vistaVidas1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(vistaPalabra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(vistaDibujo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(vistaVidas1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jugarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rendirseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(89, 89, 89)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnieButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(XButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ZButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QButtonActionPerformed
        boolean acierto = this.p.contiene('q');
        if (!acierto) {
            errores++;
        }
        this.actualizar(p);
        this.QButton.setEnabled(false);
    }//GEN-LAST:event_QButtonActionPerformed

    private void RButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RButtonActionPerformed
        boolean acierto = this.p.contiene('r');
        if (!acierto) {
            errores++;
        }
        this.actualizar(p);
        this.RButton.setEnabled(false);    }//GEN-LAST:event_RButtonActionPerformed

    private void SButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SButtonActionPerformed
        boolean acierto = this.p.contiene('s');
        if (!acierto) {
            errores++;
        }
        this.actualizar(p);
        this.SButton.setEnabled(false);    }//GEN-LAST:event_SButtonActionPerformed

    private void TButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TButtonActionPerformed
        boolean acierto = this.p.contiene('t');
        if (!acierto) {
            errores++;
        }
        this.actualizar(p);
        this.TButton.setEnabled(false);    }//GEN-LAST:event_TButtonActionPerformed

    private void UButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UButtonActionPerformed
        boolean acierto = this.p.contiene('u');
        if (!acierto) {
            errores++;
        }
        this.actualizar(p);
        this.UButton.setEnabled(false);    }//GEN-LAST:event_UButtonActionPerformed

    private void VButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VButtonActionPerformed
        boolean acierto = this.p.contiene('v');
        if (!acierto) {
            errores++;
        }
        this.actualizar(p);
        this.VButton.setEnabled(false);    }//GEN-LAST:event_VButtonActionPerformed

    private void WButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WButtonActionPerformed
        boolean acierto = this.p.contiene('w');
        if (!acierto) {
            errores++;
        }
        this.actualizar(p);
        this.WButton.setEnabled(false);    }//GEN-LAST:event_WButtonActionPerformed

    private void XButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XButtonActionPerformed
        boolean acierto = this.p.contiene('x');
        if (!acierto) {
            errores++;
        }
        this.actualizar(p);
        this.XButton.setEnabled(false);    }//GEN-LAST:event_XButtonActionPerformed

    private void YButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YButtonActionPerformed
        boolean acierto = this.p.contiene('y');
        if (!acierto) {
            errores++;
        }
        this.actualizar(p);
        this.YButton.setEnabled(false);    }//GEN-LAST:event_YButtonActionPerformed

    private void ZButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZButtonActionPerformed
        boolean acierto = this.p.contiene('z');
        if (!acierto) {
            errores++;
        }
        this.actualizar(p);
        this.ZButton.setEnabled(false);    }//GEN-LAST:event_ZButtonActionPerformed

    private void HButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HButtonActionPerformed
        boolean acierto = this.p.contiene('h');
        if (!acierto) {
            errores++;
        }
        this.actualizar(p);
        this.HButton.setEnabled(false);    }//GEN-LAST:event_HButtonActionPerformed

    private void FButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FButtonActionPerformed
        boolean acierto = this.p.contiene('F');
        if (!acierto) {
            errores++;
        }
        this.actualizar(p);
        this.FButton.setEnabled(false);    }//GEN-LAST:event_FButtonActionPerformed

    private void EButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EButtonActionPerformed
        boolean acierto = this.p.contiene('e');
        if (!acierto) {
            errores++;
        }
        this.actualizar(p);
        this.EButton.setEnabled(false);    }//GEN-LAST:event_EButtonActionPerformed

    private void JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonActionPerformed
        boolean acierto = this.p.contiene('j');
        if (!acierto) {
            errores++;
        }
        this.actualizar(p);
        this.JButton.setEnabled(false);    }//GEN-LAST:event_JButtonActionPerformed

    private void KButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KButtonActionPerformed
        boolean acierto = this.p.contiene('k');
        if (!acierto) {
            errores++;
        }
        this.actualizar(p);
        this.KButton.setEnabled(false);    }//GEN-LAST:event_KButtonActionPerformed

    private void PButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PButtonActionPerformed
        boolean acierto = this.p.contiene('p');
        if (!acierto) {
            errores++;
        }
        this.actualizar(p);
        this.PButton.setEnabled(false);    }//GEN-LAST:event_PButtonActionPerformed

    private void LButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LButtonActionPerformed
        boolean acierto = this.p.contiene('l');
        if (!acierto) {
            errores++;
        }
        this.actualizar(p);
        this.LButton.setEnabled(false);    }//GEN-LAST:event_LButtonActionPerformed

    private void MButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MButtonActionPerformed
        boolean acierto = this.p.contiene('m');
        if (!acierto) {
            errores++;
        }
        this.actualizar(p);
        this.MButton.setEnabled(false);    }//GEN-LAST:event_MButtonActionPerformed

    private void NButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NButtonActionPerformed
        boolean acierto = this.p.contiene('n');
        if (!acierto) {
            errores++;
        }
        this.actualizar(p);
        this.NButton.setEnabled(false);    }//GEN-LAST:event_NButtonActionPerformed

    private void EnieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnieButtonActionPerformed
        boolean acierto = this.p.contiene('ñ');
        if (!acierto) {
            errores++;
        }
        this.actualizar(p);
        this.EnieButton.setEnabled(false);    }//GEN-LAST:event_EnieButtonActionPerformed

    private void OButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OButtonActionPerformed
        boolean acierto = this.p.contiene('o');
        if (!acierto) {
            errores++;
        }
        this.actualizar(p);
        this.OButton.setEnabled(false);    }//GEN-LAST:event_OButtonActionPerformed

    private void BButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BButtonActionPerformed
        boolean acierto = this.p.contiene('b');
        if (!acierto) {
            errores++;
        }
        this.actualizar(p);
        this.BButton.setEnabled(false);    }//GEN-LAST:event_BButtonActionPerformed

    private void AButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AButtonActionPerformed
        boolean acierto = this.p.contiene('a');
        if (!acierto) {
            errores++;
        }
        this.actualizar(p);
        this.AButton.setEnabled(false);    }//GEN-LAST:event_AButtonActionPerformed

    private void DButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DButtonActionPerformed
        boolean acierto = this.p.contiene('d');
        if (!acierto) {
            errores++;
        }
        this.actualizar(p);
        this.DButton.setEnabled(false);    }//GEN-LAST:event_DButtonActionPerformed

    private void CButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CButtonActionPerformed
        boolean acierto = this.p.contiene('c');
        if (!acierto) {
            errores++;
        }
        this.actualizar(p);
        this.CButton.setEnabled(false);    }//GEN-LAST:event_CButtonActionPerformed

    private void GButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GButtonActionPerformed
        boolean acierto = this.p.contiene('g');
        if (!acierto) {
            errores++;
        }
        this.actualizar(p);
        this.GButton.setEnabled(false);    }//GEN-LAST:event_GButtonActionPerformed

    private void IButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IButtonActionPerformed
        boolean acierto = this.p.contiene('i');
        if (!acierto) {
            errores++;
        }
        this.actualizar(p);
        this.IButton.setEnabled(false);    }//GEN-LAST:event_IButtonActionPerformed

    private void jugarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugarButtonActionPerformed
        iniciarJuego();
    }//GEN-LAST:event_jugarButtonActionPerformed

    private void rendirseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rendirseButtonActionPerformed
        perder();
    }//GEN-LAST:event_rendirseButtonActionPerformed

    private void perder() {
        JOptionPane.showMessageDialog(this, "La palabra era " + solucion, "¡Perdiste!", JOptionPane.ERROR_MESSAGE);
        setBotones(false);
    }

    private void actualizar(Palabra nueva) {
        p = nueva;
        this.vistaPalabra1.actualizar(p);
        this.vistaVidas1.actualizar(MAX_ERRORES - errores);
        this.vistaDibujo1.actualizar(errores);
        if (p.acertada()) {
            JOptionPane.showMessageDialog(this, "¡Ganaste!", "Ahorcado", JOptionPane.INFORMATION_MESSAGE);
            setBotones(false);
        } else if (errores == MAX_ERRORES) {
            perder();
        }
        this.repaint();
        this.revalidate();
    }

    private String pedirPalabra() {
        SolicitudPalabra solicitud = new SolicitudPalabra(this, true);
        if (solicitud == null) {
            this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        }
        String resultado = solicitud.getPalabra();
        return resultado;
    }

    private void iniciarJuego() {
        solucion = pedirPalabra();
        errores = 0;
        Palabra p = new Palabra(solucion);
        setBotones(true);
        actualizar(p);
    }

    private void setBotones(boolean activar) {
        this.AButton.setEnabled(activar);
        this.BButton.setEnabled(activar);
        this.CButton.setEnabled(activar);
        this.DButton.setEnabled(activar);
        this.EButton.setEnabled(activar);
        this.FButton.setEnabled(activar);
        this.GButton.setEnabled(activar);
        this.HButton.setEnabled(activar);
        this.IButton.setEnabled(activar);
        this.JButton.setEnabled(activar);
        this.KButton.setEnabled(activar);
        this.LButton.setEnabled(activar);
        this.MButton.setEnabled(activar);
        this.NButton.setEnabled(activar);
        this.EnieButton.setEnabled(activar);
        this.OButton.setEnabled(activar);
        this.PButton.setEnabled(activar);
        this.QButton.setEnabled(activar);
        this.RButton.setEnabled(activar);
        this.SButton.setEnabled(activar);
        this.TButton.setEnabled(activar);
        this.UButton.setEnabled(activar);
        this.VButton.setEnabled(activar);
        this.WButton.setEnabled(activar);
        this.XButton.setEnabled(activar);
        this.YButton.setEnabled(activar);
        this.ZButton.setEnabled(activar);
        this.jugarButton.setEnabled(!activar);
        this.rendirseButton.setEnabled(activar);
    }

    public static void main(String args[]) {

        AhorcadoGUI controlador = new AhorcadoGUI();
        controlador.iniciarJuego();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AhorcadoGUI().setVisible(true);
            }
        });

        controlador.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AButton;
    private javax.swing.JButton BButton;
    private javax.swing.JButton CButton;
    private javax.swing.JButton DButton;
    private javax.swing.JButton EButton;
    private javax.swing.JButton EnieButton;
    private javax.swing.JButton FButton;
    private javax.swing.JButton GButton;
    private javax.swing.JButton HButton;
    private javax.swing.JButton IButton;
    private javax.swing.JButton JButton;
    private javax.swing.JButton KButton;
    private javax.swing.JButton LButton;
    private javax.swing.JButton MButton;
    private javax.swing.JButton NButton;
    private javax.swing.JButton OButton;
    private javax.swing.JButton PButton;
    private javax.swing.JButton QButton;
    private javax.swing.JButton RButton;
    private javax.swing.JButton SButton;
    private javax.swing.JButton TButton;
    private javax.swing.JButton UButton;
    private javax.swing.JButton VButton;
    private javax.swing.JButton WButton;
    private javax.swing.JButton XButton;
    private javax.swing.JButton YButton;
    private javax.swing.JButton ZButton;
    private javax.swing.JButton jugarButton;
    private javax.swing.JButton rendirseButton;
    private InterfazGrafica.VistaDibujo vistaDibujo1;
    private InterfazGrafica.VistaPalabra vistaPalabra1;
    private InterfazGrafica.VistaVidas vistaVidas1;
    // End of variables declaration//GEN-END:variables
}
